config system external-resource
    edit "AWS_GeoIP_ALL"
        set status enable
        set type address
        set resource "https://raw.githubusercontent.com/yuvalg72/AWS_GeoIPs_External_IP_Feed/main/feeds/ipv4/all.txt"
        set refresh-rate 1440
        set server-identity-check full
        set comments "AWS Geographic IPv4 ranges - All geolocated AWS prefixes"
    next
    edit "AWS_GeoIP_US"
        set status enable
        set type address
        set resource "https://raw.githubusercontent.com/yuvalg72/AWS_GeoIPs_External_IP_Feed/main/feeds/ipv4/countries/US.txt"
        set refresh-rate 1440
        set server-identity-check full
        set comments "AWS Geographic IPs USA Only"
    next
    edit "AWS_GeoIP_US-OH"
        set status enable
        set type address
        set resource "https://raw.githubusercontent.com/yuvalg72/AWS_GeoIPs_External_IP_Feed/main/feeds/ipv4/subdivisions/US-OH.txt"
        set refresh-rate 1440
        set server-identity-check full
        set comments "AWS Geographic IPs USA Ohio Only"
    next
    edit "AWS_GeoIP_US-EAST-1"
        set status enable
        set type address
        set resource "https://raw.githubusercontent.com/yuvalg72/AWS_GeoIPs_External_IP_Feed/main/feeds/ipv4/aws-regions/us-east-1.txt"
        set refresh-rate 1440
        set server-identity-check full
        set comments "AWS IP ranges for AWS Region us-east-1"
    next
end
